function kpi(icon,label,value,note,target,cls='',progress=null){return `<article class="kpi-card" data-go="${target}"><div class="kpi-top"><div class="kpi-icon">${ICONS[icon]}</div><div><div class="kpi-label">${esc(label)}</div><div class="kpi-value">${esc(value)}</div></div></div><div class="kpi-note ${cls}">${note}</div>${progress!==null?`<div class="mini-progress"><i style="width:${Math.max(0,Math.min(100,progress))}%"></i></div>`:''}</article>`}
function dashboard(){const m=calc(),permitPct=m.permits.length?Math.round(m.cleared/m.permits.length*100):0;const critical=m.open.filter(t=>t.priority==='Critical').length;return `<div class="kpi-grid">
${kpi('tasks','Open Tasks',m.open.length,`${critical} critical items`,'tasks',critical?'warn':'good')}
${kpi('decision','Open Decisions',m.decisions.length,'Core approvals still need input','decisions','warn')}
${kpi('shield','Permits Cleared',`${m.cleared} / ${m.permits.length}`,`${permitPct}% cleared / not required`,'permits','',permitPct)}
${kpi('users','Live Signups',m.signups,'Synced from live Google Doc','signups','good')}
${kpi('money','Planned Costs',money(m.expenses),'Revenue assumptions still TBD','budget','warn')}
${kpi('trophy','Sponsor Opportunities',m.ops,'Pricing and packages in planning','opportunities')}
</div>
<div class="roadmap-strip"><div class="roadmap-score"><div class="score-ring" style="--score:${m.readiness}"><b>${m.readiness}</b></div><span><strong>Operational Readiness</strong><small>Derived from live task, permit & decision statuses</small></span></div><div class="milestones"><div class="milestone critical"><span class="milestone-dot">1</span><strong>Date + Entity</strong><small>Decision needed</small></div><div class="milestone critical"><span class="milestone-dot">2</span><strong>Course</strong><small>Verify next</small></div><div class="milestone next"><span class="milestone-dot">3</span><strong>Permits</strong><small>Start after course</small></div><div class="milestone"><span class="milestone-dot">4</span><strong>Registration</strong><small>Platform TBD</small></div><div class="milestone"><span class="milestone-dot">5</span><strong>Race Day</strong><small>Fall 2027 · date TBD</small></div></div></div>
<div class="dashboard-grid">
<section class="panel tasks-panel"><div class="panel-head"><div class="panel-title">Top Priority Tasks</div><button class="panel-link" data-go="tasks">View all tasks</button></div><div class="task-list">${m.open.slice(0,5).map(taskRow).join('')}</div></section>
<section class="panel permits-panel"><div class="panel-head"><div class="panel-title">Permits & Safety Progress</div><button class="panel-link" data-go="permits">View all</button></div>${permitChart(m)}</section>
<section class="panel quick-panel"><div class="panel-head"><div class="panel-title">Quick Actions</div></div>${quickActions()}</section>
<section class="panel budget-panel"><div class="panel-head"><div class="panel-title">Budget Snapshot</div><button class="panel-link" data-go="budget">View details</button></div>${budgetChart(m)}</section>
<section class="panel sponsor-panel"><div class="panel-head"><div class="panel-title">Sponsor Opportunity Inventory</div><button class="panel-link" data-go="opportunities">View inventory</button></div>${sponsorChart()}</section>
<section class="panel activity-panel"><div class="panel-head"><div class="panel-title">Recent Activity / AI Updates</div><button class="panel-link" data-go="activity">View all</button></div>${activityFeed(m)}</section>
</div>
<div class="status-strip"><div class="status-item"><small>Race Date</small><strong>Fall 2027 · TBD</strong></div><div class="status-item"><small>Master Plan</small><strong>${(data.chapters||[]).length} chapters</strong></div><div class="status-item"><small>Open Tasks</small><strong>${m.open.length}</strong></div><div class="status-item"><small>Permits</small><strong>${m.cleared} / ${m.permits.length} cleared</strong></div><div class="status-item"><small>Sponsor Ops</small><strong>${m.ops}</strong></div><div class="status-item"><small>Live Signups</small><strong>${m.signups}</strong></div></div>`}
function taskRow(t){const pc=t.priority==='Critical'?'priority-critical':t.priority==='High'?'priority-high':'priority-medium';const dot=t.priority==='Critical'?'var(--red)':t.priority==='High'?'var(--orange)':'#e7bd25';return `<div class="task-row" data-edit="tasks" data-id="${esc(t.id)}"><span class="task-dot" style="background:${dot}"></span><span class="task-priority ${pc}">${esc(t.priority||'Medium')}</span><span class="task-main"><strong>${esc(t.title)}</strong><small>${esc(t.category||'General')} · ${esc(t.owner_name||'Unassigned')}</small></span><span class="task-status ${t.status==='In Progress'?'in-progress':''}">${esc(t.status||'')}</span></div>`}
function permitChart(m){const pct=m.permits.length?m.cleared/m.permits.length*100:0;const not=m.permits.length-m.cleared;return `<div class="chart-wrap"><div class="donut-layout"><div class="donut" style="background:conic-gradient(var(--green) 0 ${pct}%,#d0cbd3 ${pct}% 100%)"><div class="donut-center"><strong>${m.cleared}</strong><small>of ${m.permits.length}</small></div></div><div class="legend"><div class="legend-row"><span class="legend-dot" style="background:var(--green)"></span><span>Cleared / Not Required</span><b>${m.cleared} (${Math.round(pct)}%)</b></div><div class="legend-row"><span class="legend-dot" style="background:#c7c2ca"></span><span>Not Started</span><b>${not}</b></div></div></div><div class="panel-foot"><span class="${m.cleared?'on-track':''}">${m.cleared?'● Foundation started':'● Needs attention'}</span><span>Final date/course still required</span></div></div>`}
function budgetChart(m){const cat={};for(const b of data.budget_lines||[]){if(b.line_type==='Expense')cat[b.category]=(cat[b.category]||0)+Number(b.budget_amount||0)}const publicSafety=(cat['Public Safety']||0)+(cat['Race Operations']||0),production=cat['Production']||0,festival=cat['Festival']||0,other=Math.max(0,m.expenses-publicSafety-production-festival);const rows=[['Public Safety + Timing',publicSafety,'#60208b'],['Production',production,'#9d6ab9'],['Festival',festival,'#e6ac25'],['Other planned costs',other,'#a6a4a9']];return `<div class="budget-content"><div class="budget-top"><div class="budget-donut"><div class="budget-center"><strong>${money(m.expenses)}</strong><small>planned costs</small></div></div><div class="budget-bars">${rows.map(([n,v,c])=>`<div class="bar-row"><strong><span>${n}</span><span>${money(v)}</span></strong><div class="bar-track"><i style="width:${m.expenses?v/m.expenses*100:0}%;background:${c}"></i></div></div>`).join('')}</div></div><div class="panel-foot"><span>Actual spend: ${money(m.actual)}</span><span>Revenue model: TBD</span></div></div>`}
function sponsorChart(){const ops=data.sponsor_opportunities||[],activation=ops.filter(x=>x.opportunity_type==='Activation').length,tier=ops.filter(x=>x.opportunity_type==='Tier').length,inkind=ops.filter(x=>x.opportunity_type==='In-Kind').length;return `<div class="funnel-area"><div class="funnel"><div class="funnel-piece one"></div><div class="funnel-piece two"></div><div class="funnel-piece three"></div><div class="funnel-piece four"></div></div><div class="legend"><div class="legend-row"><span class="legend-dot" style="background:#471361"></span><span>All Opportunities</span><b>${ops.length}</b></div><div class="legend-row"><span class="legend-dot" style="background:#7130a2"></span><span>Activations</span><b>${activation}</b></div><div class="legend-row"><span class="legend-dot" style="background:#e5aa2c"></span><span>Sponsor Tiers</span><b>${tier}</b></div><div class="legend-row"><span class="legend-dot" style="background:#a8a6aa"></span><span>In-Kind</span><b>${inkind}</b></div></div><div class="panel-foot" style="grid-column:1/-1"><span>Pricing</span><b style="color:#5d1b80">TBD</b></div></div>`}
function quickActions(){return `<div class="quick-grid"><button class="quick-action" data-add="tasks"><span>＋</span>Add Task</button><button class="quick-action" data-page-link="sponsors"><span>♜</span>Add Sponsor</button><button class="quick-action" data-external="${CURRENT_PORTAL}/marketing.html"><span>⌁</span>Create Marketing Piece</button><button class="quick-action" data-external="${CURRENT_PORTAL}/master.html"><span>▤</span>Open Master Doc</button><button class="quick-action" data-page-link="website"><span>◎</span>Edit Website</button><button class="quick-action" data-page-link="signups"><span>◉</span>Review Signups</button></div>`}
function activityFeed(m){const rows=[['purple','✦','AI / Portal','AI and portal integration work is active','Today'],['green','✓','Master Plan Synced',`${(data.chapters||[]).length} chapters available in the live master`,'Today'],['purple','＋','Live Signups',`${m.signups} committee-interest records synced`,'Today'],['gold','$','Budget Model',`${money(m.expenses)} in current planned expenses`,'Today'],['purple','◆','Marketing Library',`${(data.marketing_assets||[]).length} branded assets stored so far`,'Today']];return `<div class="activity-list">${rows.map(r=>`<div class="activity"><span class="activity-icon ${r[0]}">${r[1]}</span><span class="activity-copy"><strong>${r[2]}</strong><small>${r[3]}</small></span><time>${r[4]}</time></div>`).join('')}</div>`}