const BASE='https://vofnxwgjqxgahjiobtqw.supabase.co';
const KEY='sb_publishable_oEUGCcdpWX94DD7wOZv5Pw_3d8O6Bog';
const AI_URL='https://xlaawvuyfbyefkinsrjs.supabase.co/functions/v1/taylor5k-ai';
const AI_KEY='sb_publishable_lwsk4TTaXHzBeB6GEMlwGg_4kdhDWA3';
const SESSION_KEY='t5k_session';
const CURRENT_PORTAL='https://taylor-5k-planning-portal.vercel.app';
let session=null, me=null, data={}, currentPage='dashboard', editing=null, voiceReplies=true, recognition=null, aiBusy=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)||0);
const DEMO=new URLSearchParams(location.search).has('demo')||location.protocol==='file:';
const ICONS={
dashboard:'<svg viewBox="0 0 24 24" fill="none"><path d="M3 11.2 12 4l9 7.2V21H3z"/><path d="M9 21v-6h6v6"/></svg>',
users:'<svg viewBox="0 0 24 24" fill="none"><circle cx="9" cy="8" r="4"/><path d="M2.5 21c.7-5 3-7.5 6.5-7.5S14.8 16 15.5 21"/><path d="M15 5.5a3 3 0 0 1 0 5.5M17 14c2.6.5 4 2.8 4.5 6"/></svg>',
doc:'<svg viewBox="0 0 24 24" fill="none"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5M9 12h6M9 16h6"/></svg>',
tasks:'<svg viewBox="0 0 24 24" fill="none"><rect x="4" y="3" width="16" height="18" rx="2"/><path d="m8 8 1.5 1.5L12 7M8 13l1.5 1.5L12 12M14 9h3M14 14h3"/></svg>',
money:'<svg viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9"/><path d="M15 8.5c-.7-.8-1.7-1.2-3-1.2-1.6 0-2.8.8-2.8 2 0 3 5.7 1.7 5.7 4.9 0 1.3-1.2 2.2-3 2.2-1.3 0-2.5-.4-3.4-1.3M12 5.5v13"/></svg>',
shield:'<svg viewBox="0 0 24 24" fill="none"><path d="M12 3 20 6v5c0 5-3.2 8.4-8 10-4.8-1.6-8-5-8-10V6z"/><path d="m8.5 12 2 2 5-5"/></svg>',
megaphone:'<svg viewBox="0 0 24 24" fill="none"><path d="M4 10v4h4l9 4V6L8 10z"/><path d="m8 14 1.5 5h3"/></svg>',
globe:'<svg viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.6 2.5 4 5.5 4 9s-1.4 6.5-4 9c-2.6-2.5-4-5.5-4-9s1.4-6.5 4-9"/></svg>',
trophy:'<svg viewBox="0 0 24 24" fill="none"><path d="M8 4h8v5c0 3-1.5 5-4 6-2.5-1-4-3-4-6zM12 15v4M8 21h8"/><path d="M8 6H4c0 4 1.5 6 4.5 6M16 6h4c0 4-1.5 6-4.5 6"/></svg>',
festival:'<svg viewBox="0 0 24 24" fill="none"><path d="m4 10 2-5h12l2 5M5 10v10h14V10"/><path d="M9 20v-6h6v6M4 10c1 2 3 2 4 0 1 2 3 2 4 0 1 2 3 2 4 0 1 2 3 2 4 0"/></svg>',
swag:'<svg viewBox="0 0 24 24" fill="none"><path d="m8 4 4 2 4-2 4 5-4 2v10H8V11L4 9z"/></svg>',
decision:'<svg viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9"/><path d="M9.7 9a2.5 2.5 0 0 1 4.8 1c0 2-2.5 2.2-2.5 4M12 17h.01"/></svg>',
activity:'<svg viewBox="0 0 24 24" fill="none"><path d="M4 19V9M10 19V5M16 19v-7M22 19H2"/></svg>'
};
const navItems=[
['dashboard','Dashboard','dashboard'],['signups','Live Signups','users'],['plan','Master Plan','doc'],['masterdoc','Full Master Planning Doc','doc',CURRENT_PORTAL+'/master.html'],['tasks','Tasks','tasks'],['decisions','Open Decisions','decision'],['budget','Budget','money'],['permits','Permits & Safety','shield'],['sponsors','Sponsor Pipeline','trophy'],['opportunities','Sponsor Opportunities','trophy'],['festival','Community Festival','festival'],['swag','Runner Swag','swag'],['marketing','Marketing Library','megaphone',CURRENT_PORTAL+'/marketing.html'],['website','Website','globe'],['team','Team & Access','users'],['activity','Audit / AI Activity','activity']
];
const mobileItems=[['dashboard','Dashboard','dashboard'],['tasks','Tasks','tasks'],['marketing','Marketing','megaphone'],['website','Website','globe'],['ai','AI','activity']];
function headers(){return {apikey:KEY,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'}};
async function api(path,opt={}){const r=await fetch(BASE+path,{...opt,headers:{...headers(),...(opt.headers||{})}});let j=null;try{j=await r.json()}catch{}if(!r.ok)throw Error(j?.message||j?.msg||j?.error_description||`Request failed ${r.status}`);return j}
async function signIn(email,password){const r=await fetch(BASE+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const j=await r.json();if(!r.ok)throw Error(j.error_description||j.msg||'Sign in failed');session={access_token:j.access_token,refresh_token:j.refresh_token,user:j.user};localStorage.setItem(SESSION_KEY,JSON.stringify(session))}
const demoData={
tasks:[
{id:'77af',title:'Confirm legal operating entity, beneficiary and fundraising structure',category:'Finance / Compliance',owner_name:'Unassigned',due_date:null,status:'Decision Required',priority:'Critical',notes:'Confirm operating entity, beneficiary, bank/payment flow, contract-signing authority and Massachusetts charitable-solicitation requirements before accepting public donations.'},
{id:'2a4d',title:'Create Fall 2027 date shortlist and begin calendar checks',category:'Event Date / Approvals',owner_name:'Unassigned',due_date:null,status:'Not Started',priority:'Critical',notes:'Create a shortlist of 2–4 preferred Fall 2027 dates and begin Norton Public Schools / Town / Police / Fire calendar checks.'},
{id:'d51a',title:'Select and physically verify preferred course for Police/Fire review',category:'Course / Public Safety',owner_name:'Unassigned',due_date:null,status:'Not Started',priority:'Critical',notes:'Select the preferred course concept, physically verify it and take a detailed route/site map to preliminary Police/Fire review.'},
{id:'b8c7',title:'Obtain first budget quotes and replace planning placeholders',category:'Budget',owner_name:'Chris',due_date:null,status:'In Progress',priority:'High',notes:'Chapter 15 working P&L is loaded. Obtain first quotes and replace estimates.'},
{id:'236c',title:'Set year-one public participant cap',category:'Capacity / Operations',owner_name:'Unassigned',due_date:null,status:'Decision Required',priority:'High',notes:'Set the registration cap after route, parking, bathrooms, medical, Police and finish-area capacity are understood.'},
{id:'8fa3',title:'Finalize registration platform, pricing and participant policies',category:'Registration',owner_name:'Unassigned',due_date:null,status:'Not Started',priority:'High',notes:'Finalize platform, pricing ladder, refund/transfer/weather policy and waiver workflow.'},
{id:'9736',title:'Document Mercury Timing scope and data workflow',category:'Timing / Registration',owner_name:'Unassigned',due_date:null,status:'Not Started',priority:'High',notes:'Confirm participant fields, bib process, timing footprint, results display and awards workflow.'},
{id:'5005',title:'Finalize sponsor prospectus and pricing',category:'Sponsors',owner_name:'Unassigned',due_date:null,status:'Not Started',priority:'High',notes:'Use the working P&L and sponsor inventory to finalize packages and pricing.'},
{id:'162a',title:'Complete committee login rollout and add second Super Admin',category:'Planning Portal',owner_name:'Chris',due_date:null,status:'In Progress',priority:'High',notes:'Secure login is active. Complete committee role rollout.'},
{id:'0920',title:'Finish AI Copilot production integration',category:'Planning Portal / AI',owner_name:'Chris',due_date:null,status:'In Progress',priority:'High',notes:'Complete internal-data tools, outside research, voice mode and confirmations.'},
{id:'3e6a',title:'Create initial Emergency Action Plan and communications structure',category:'Safety / Medical',owner_name:'Unassigned',due_date:null,status:'Not Started',priority:'High',notes:'Create medical/public-safety concept, command structure, radio plan and weather/AQI process.'},
{id:'58de',title:'Draft volunteer staffing matrix and identify team leads',category:'Volunteers',owner_name:'Unassigned',due_date:null,status:'Not Started',priority:'Medium',notes:'Draft staffing by course post, start/finish, registration, hydration, parking, festival, setup and teardown.'},
{id:'d689',title:'Obtain runner swag, sanitation, festival and production quotes',category:'Quotes / Procurement',owner_name:'Unassigned',due_date:null,status:'Not Started',priority:'High',notes:'Obtain initial quotes to test the 500-runner baseline.'}
],
permits:[...Array(12)].map((_,i)=>({id:'p'+i,approval:['Alcohol on school property','Event liability insurance / COIs','Food trucks / propane / fire permits','Food vendor / Board of Health compliance','MassDOT event notification','Norton Fire / EMS approval','Norton Police route & traffic approval','Norton Public Schools facility / track use','Parking / signs / entertainment approvals','Participant / minor / volunteer waivers','Town Special Events / Parade Permit','Traffic Management Plan / barricades'][i],authority:'Planning authority',owner_name:null,due_date:null,status:i===0?'Not Required':'Not Started',notes:'Current planning requirement.'})),
sponsors:[],
sponsor_opportunities:[...Array(16)].map((_,i)=>({id:'o'+i,opportunity_type:i<11?'Activation':i<15?'Tier':'In-Kind',name:['Community Stage presented by ___','Finish Festival presented by ___','Finisher Medal Sponsor','Hydration Station sponsored by ___','Kids Fun Run presented by ___','Kids Zone presented by ___','Official Race Shirt Sponsor','Photo Experience sponsored by ___','Runner Bag / Packet Sponsor','Track Challenge presented by ___','Volunteer Shirt Sponsor','Community Sponsor','Gold / Major Sponsor','Presenting / Lead Sponsor','Purple / Supporting Sponsor','In-Kind Partner'][i],target_amount:0,status:'Planning'})),
budget_lines:[
['Expense','Administration','Administration / misc.',300],['Expense','Awards','Awards',500],['Expense','Course','Course measurement / certification',500],['Expense','Festival','Community Festival',1500],['Expense','Festival','Kids Fun Run / family activities',500],['Expense','Insurance','Event liability insurance',750],['Expense','Marketing','Marketing / printing',750],['Expense','Media','Photography / video',750],['Expense','Permits','Permits & approvals',400],['Expense','Production','PA / DJ / announcer support',750],['Expense','Production','Signage / banners / course print',1200],['Expense','Production','Tents / tables / power / production',1500],['Expense','Public Safety','Fire / EMS / medical',1000],['Expense','Public Safety','Police / traffic control',3000],['Expense','Race Operations','Timing & race services',3000],['Expense','Site','Sanitation',1200],['Expense','Technology','Technology / planning systems',520]
].map((x,i)=>({id:'b'+i,line_type:x[0],category:x[1],item:x[2],budget_amount:x[3],actual_amount:0,paid_status:'Not Paid',owner_name:'TBD',vendor:null})),
decisions:['Exact race date / start time','Legal operating entity / beneficiary','Final course / Police acceptance','Registration platform / pricing','Year-one participant cap','Insurance / sanction route','Sponsor pricing / underwriting plan','Community Village final scope','Kids Fun Run format','Awards / age groups','Vendor policy / fees'].map((t,i)=>({id:'d'+i,title:t,status:'Open',context:'Decision required to unlock downstream planning.',decision:null,decided_at:null})),
chapters:[...Array(18)].map((_,i)=>({id:'c'+(i+1),chapter_no:i+1,title:['Executive Summary','Event Identity & Experience','Course & Venue Planning','Permits, Insurance & Public Safety Approvals','Website, Registration & Communications','Timing, Results & Course Operations','Sponsors, Vendors & Fundraising','Organization, Finance & Fundraising Compliance','Runner Swag, Awards & Merchandise','Spectator, Family & Community Festival Experience','Race-Day Operations & Run of Show','Volunteers, Communications & Medical Plan','Participant Experience, Accessibility & Policies','Production, Equipment & Post-Race Closeout','Working Budget, Financial Model & Master Timeline','Immediate Action Plan & Current Status','Approved Brand Identity — Option 4 Refined','Planning Portal, Collaboration & AI Copilot'][i],body:`Chapter ${i+1} live planning content. In the production portal this is loaded from the shared master plan database.`,status:'editable'})),
team_members:[{id:'t1',display_name:'Chris',email:'cstrynar@gmail.com',role:'super_admin',active:true,protected:true},{id:'t2',display_name:'Dr. Todd Kefor',email:'tkefor@norton.k12.ma.us',role:'super_admin',active:true,protected:false}],
festival_items:[],swag_items:[],site_edits:[],marketing_assets:[],audit_log:[],ai_activity:[],
live_signups:{ok:true,count:6,fetched_at:new Date().toISOString(),rows:[{name:'Christopher Fielding',email:'Christopher.fielding@mass.gov',role:'Post Race celebration Ops / communications / general support',summary:'Taunton crew will support and focus on a post-race function.',phone:''},{name:'Chris Strynar',email:'cstrynar@gmail.com',role:'Timing, race support, medals, marketing',summary:'Mercury Timing can help as needed.',phone:'508-277-3516'},{name:'Aaron Sumner',email:'asumner@norton.k12.ma.us',role:'Organization / logistics',summary:'Site coordination, NPS resources, transportation and athletic-team outreach.',phone:'508-344-6789'},{name:'Vinny Cerce',email:'vcerce@norton.k12.ma.us',role:'School Department Liaison',summary:'Coordinate school support and town contacts.',phone:'508-641-3146'},{name:'Brooke-Lynn Williams',email:'blwilliams44@outlook.com',role:'Event planning / marketing / registration / social media',summary:'Create, share and document the event.',phone:''},{name:'Jesse Shaughnessy',email:'jesseshaughnessy@norton.k12.ma.us',role:'Organization / promotion',summary:'Coordinate NPS staff and town/school support.',phone:'781-690-3091'}]}
};
async function loadData(){if(DEMO){me={display_name:'Chris',email:'cstrynar@gmail.com',role:'super_admin',active:true};session={access_token:'demo',user:{id:'demo'}};data=structuredClone(demoData);return}
const user=await api('/auth/v1/user');session.user=user;const members=await api('/rest/v1/team_members?select=*&user_id=eq.'+encodeURIComponent(user.id)+'&active=eq.true&limit=1');me=members[0];if(!me)throw Error('Your account is not linked to an active Taylor 5K role.');
const paths={chapters:'/rest/v1/chapters?select=*&order=chapter_no.asc',tasks:'/rest/v1/tasks?select=*&order=created_at.asc',permits:'/rest/v1/permits?select=*&order=approval.asc',sponsors:'/rest/v1/sponsors?select=*&order=updated_at.desc',sponsor_opportunities:'/rest/v1/sponsor_opportunities?select=*&order=opportunity_type.asc,name.asc',festival_items:'/rest/v1/festival_items?select=*&order=name.asc',swag_items:'/rest/v1/swag_items?select=*&order=item.asc',decisions:'/rest/v1/decisions?select=*&order=created_at.asc',team_members:'/rest/v1/team_members?select=*&active=eq.true&order=added_at.asc',site_edits:'/rest/v1/site_edits?select=*&order=created_at.desc',marketing_assets:'/rest/v1/marketing_assets?select=*&order=updated_at.desc'};if(['super_admin','admin'].includes(me.role))paths.budget_lines='/rest/v1/budget_lines?select=*&order=line_type.desc,category.asc,item.asc';else data.budget_lines=[];for(const [k,p] of Object.entries(paths)){try{data[k]=await api(p)}catch{data[k]=[]}}
try{data.live_signups=await fetch(CURRENT_PORTAL+'/api/signups?ts='+Date.now(),{cache:'no-store'}).then(r=>r.json())}catch{data.live_signups={ok:false,count:0,rows:[]}}
try{if(['super_admin','admin'].includes(me.role)){data.audit_log=await api('/rest/v1/audit_log?select=*&order=created_at.desc&limit=12');data.ai_activity=await api('/rest/v1/ai_activity?select=*&order=created_at.desc&limit=12')}}catch{}
}
function renderNav(){const nav=$('#sidebarNav');nav.innerHTML=navItems.filter(x=>x[0]!=='budget'||['super_admin','admin'].includes(me.role)).map(([id,label,icon,url])=>`<button class="nav-item ${id===currentPage?'active':''}" ${url?`data-nav-external="${url}"`:`data-page="${id}"`}>${ICONS[icon]}<span>${label}</span></button>`).join('');nav.onclick=e=>{const ext=e.target.closest('[data-nav-external]');if(ext){window.open(ext.dataset.navExternal,'_blank','noopener');return}const b=e.target.closest('[data-page]');if(b){currentPage=b.dataset.page;renderPage()}};
const mobile=$('#mobileNav');mobile.innerHTML=mobileItems.map(([id,label,icon])=>`<button class="mobile-tab ${id===currentPage?'active':''}" data-mobile="${id}">${ICONS[icon]}<span>${label}</span></button>`).join('');mobile.onclick=e=>{const b=e.target.closest('[data-mobile]');if(!b)return;const id=b.dataset.mobile;if(id==='ai')openAI();else if(id==='marketing')window.open(CURRENT_PORTAL+'/marketing.html','_blank');else{currentPage=id;renderPage()}}}
function setIdentity(){const name=me.display_name||me.email||'Committee Member';$('#profileName').textContent=name;$('#profileRole').textContent=roleLabel(me.role);$('#profileInitials').textContent=initials(name);if($('#mobileAvatar'))$('#mobileAvatar').textContent=initials(name);$('#welcomeText').innerHTML=`Welcome back, ${esc(firstName(name))}! <span>👋</span>`;$('#aiRolePill').textContent=roleLabel(me.role).toUpperCase()+' AI'}
function firstName(n){return String(n).trim().split(/\s+/)[0]||'there'}function initials(n){return String(n).trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'KT'}function roleLabel(r){return({super_admin:'Super Admin',admin:'Administrator',editor:'Editor',viewer:'Viewer'})[r]||r||'Member'}
function calc(){const tasks=data.tasks||[],open=tasks.filter(t=>String(t.status).toLowerCase()!=='complete'),decisions=(data.decisions||[]).filter(d=>String(d.status).toLowerCase()==='open'),permits=data.permits||[],cleared=permits.filter(p=>['Approved','Not Required'].includes(p.status)).length,expenses=(data.budget_lines||[]).filter(b=>b.line_type==='Expense').reduce((a,b)=>a+Number(b.budget_amount||0),0),actual=(data.budget_lines||[]).filter(b=>b.line_type==='Expense').reduce((a,b)=>a+Number(b.actual_amount||0),0),ops=(data.sponsor_opportunities||[]).length,marketing=(data.marketing_assets||[]).length,signups=data.live_signups?.count||0;
const taskProgress=tasks.length?tasks.reduce((s,t)=>s+({'complete':1,'in progress':.55,'decision required':.15,'waiting':.25,'not started':0}[String(t.status).toLowerCase()]??.1),0)/tasks.length:0;const permitProgress=permits.length?cleared/permits.length:0;const decisionProgress=(data.decisions||[]).length?((data.decisions||[]).length-decisions.length)/(data.decisions||[]).length:0;const readiness=Math.round((taskProgress*.45+permitProgress*.35+decisionProgress*.20)*100);return{tasks,open,decisions,permits,cleared,expenses,actual,ops,marketing,signups,readiness}}